import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '../header'
import Navbar from '../navbar'
import Footer from '../footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div>
                    <Header />
                    <div className='flex h-screen'>
                        <Navbar />
                        {children}
                    </div>
                    <Footer />
                </div>
            </body>
        </html>
    )
}
